package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDiscoverFromResolvConf(t *testing.T) {
	tests := []struct {
		name           string
		content        string
		wantSite       string
		wantTenant     string
		wantRegion     string
	}{
		{
			name: "F5 XC full search list",
			content: `# generated by xc
nameserver 169.254.20.10
search tawon-operator.svc.srikan-tf-test-0.platform-svc-nbryikfr.tenant.local svc.srikan-tf-test-0.platform-svc-nbryikfr.tenant.local srikan-tf-test-0.platform-svc-nbryikfr.tenant.local us-east-2.compute.internal
options ndots:5
`,
			wantSite:   "srikan-tf-test-0",
			wantTenant: "platform-svc-nbryikfr",
			wantRegion: "us-east-2",
		},
		{
			name: "only the four-label site+tenant token yields identity",
			content: `search srikan-tf-test-0.platform-svc-nbryikfr.tenant.local
`,
			wantSite:   "srikan-tf-test-0",
			wantTenant: "platform-svc-nbryikfr",
		},
		{
			name: "longer tenant.local tokens are ignored for identity",
			content: `search ns.svc.srikan-tf-test-0.platform-svc-nbryikfr.tenant.local svc.srikan-tf-test-0.platform-svc-nbryikfr.tenant.local
`,
		},
		{
			name: "no resolv.conf content",
			content: `nameserver 1.1.1.1
`,
		},
		{
			name: "region only",
			content: `search us-west-1.compute.internal
`,
			wantRegion: "us-west-1",
		},
		{
			name: "first match wins",
			content: `search foo.bar.tenant.local baz.qux.tenant.local
`,
			wantSite:   "foo",
			wantTenant: "bar",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			path := filepath.Join(dir, "resolv.conf")
			if err := os.WriteFile(path, []byte(tc.content), 0o644); err != nil {
				t.Fatal(err)
			}
			old := resolvConfPath
			resolvConfPath = path
			t.Cleanup(func() { resolvConfPath = old })

			site, tenant, region := discoverFromResolvConf()
			if site != tc.wantSite {
				t.Errorf("site=%q, want %q", site, tc.wantSite)
			}
			if tenant != tc.wantTenant {
				t.Errorf("tenant=%q, want %q", tenant, tc.wantTenant)
			}
			if region != tc.wantRegion {
				t.Errorf("region=%q, want %q", region, tc.wantRegion)
			}
		})
	}
}

func TestDiscoverFromResolvConf_MissingFile(t *testing.T) {
	old := resolvConfPath
	resolvConfPath = "/does/not/exist/resolv.conf"
	t.Cleanup(func() { resolvConfPath = old })

	site, tenant, region := discoverFromResolvConf()
	if site != "" || tenant != "" || region != "" {
		t.Errorf("expected all empty on missing file, got %q/%q/%q", site, tenant, region)
	}
}

func TestFromEnv_DiscoveryFallsBackBehindEnv(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	content := `search discovered-site.discovered-tenant.tenant.local us-east-2.compute.internal
`
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	old := resolvConfPath
	resolvConfPath = path
	t.Cleanup(func() { resolvConfPath = old })

	t.Setenv("EOB_SITE_ID", "explicit-site")
	t.Setenv("EOB_TENANT", "")
	t.Setenv("EOB_REGION", "")

	cfg := FromEnv("v0")
	if cfg.SiteID != "explicit-site" {
		t.Errorf("env should win for SiteID; got %q", cfg.SiteID)
	}
	if cfg.Tenant != "discovered-tenant" {
		t.Errorf("discovery should fill Tenant; got %q", cfg.Tenant)
	}
	if cfg.Region != "us-east-2" {
		t.Errorf("discovery should fill Region; got %q", cfg.Region)
	}
}
